# Generated by Django 4.2.20 on 2025-04-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='escola',
        ),
        migrations.AddField(
            model_name='alunos',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='educacao.turmas'),
            preserve_default=False,
        ),
    ]
