# Generated by Django 4.2.20 on 2025-04-15 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_pessoa_user_inclusao'),
        ('educacao', '0002_remove_alunos_escola_alunos_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='turmas',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_professor', to='autenticacao.pessoa'),
        ),
    ]
