# Generated by Django 4.2.20 on 2025-04-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0003_turmas_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'ordering': ['nome']},
        ),
    ]
