# Generated by Django 4.2.20 on 2025-04-28 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educacao', '0004_alter_alunos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_avaliacoes',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='arquivo',
            field=models.FileField(null=True, upload_to='caminho/desejado/'),
        ),
        migrations.CreateModel(
            name='Componente_Curricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_edicao', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200)),
                ('user_edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_edicao', to=settings.AUTH_USER_MODEL)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tipo_avaliacoes',
            name='componente_curricular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componente_curricular', to='educacao.componente_curricular'),
        ),
    ]
