# Generated by Django 4.2.20 on 2025-05-06 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educacao', '0009_alunos_detalhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunosTurmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_edicao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('matriculado', 'Matriculado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('transferido', 'Transferido')], default='matriculado', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='nivel_ensino',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='turmas',
            options={'ordering': ['-ano', 'nome']},
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='avaliacao1',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='avaliacao2',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='avaliacao3',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='avaliacao4',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='detalhe',
        ),
        migrations.RemoveField(
            model_name='alunos',
            name='turma',
        ),
        migrations.CreateModel(
            name='Resultado_Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_edicao', models.DateTimeField(auto_now=True)),
                ('avaliacao1', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('avaliacao2', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('avaliacao3', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('avaliacao4', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('media_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('aprovado', models.BooleanField(default=False)),
                ('data', models.DateField(auto_now_add=True)),
                ('aluno_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='educacao.alunosturmas')),
                ('tipo_avaliacoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_avaliacoes', to='educacao.tipo_avaliacoes')),
                ('user_edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_edicao', to=settings.AUTH_USER_MODEL)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservacoesAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('dt_edicao', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('laudo', 'Laudo'), ('comportamento', 'Comportamento'), ('saude', 'Saúde'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('eh_especial', models.BooleanField(default=False, verbose_name='É especial?')),
                ('descricao', models.TextField(verbose_name='Descrição da observação')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='educacao.alunos')),
                ('user_edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_edicao', to=settings.AUTH_USER_MODEL)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alunosturmas',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='educacao.alunos'),
        ),
        migrations.AddField(
            model_name='alunosturmas',
            name='ano_letivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ano_letivo', to='educacao.nivel_ensino'),
        ),
        migrations.AddField(
            model_name='alunosturmas',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos_turma', to='educacao.turmas'),
        ),
        migrations.AddField(
            model_name='alunosturmas',
            name='user_edicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_edicao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alunosturmas',
            name='user_inclusao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_inclusao', to=settings.AUTH_USER_MODEL),
        ),
    ]
