# Generated by Django 4.2.20 on 2025-05-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0010_alunosturmas_alter_nivel_ensino_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunosturmas',
            name='ano_letivo',
        ),
    ]
