# Generated by Django 4.2.20 on 2025-05-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0011_remove_alunosturmas_ano_letivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultado_avaliacoes',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='resultado_avaliacoes',
            name='tipo_avaliacoes',
        ),
    ]
