# Generated by Django 4.2.20 on 2025-05-06 17:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educacao', '0013_remove_observacoesaluno_eh_especial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlunosTurmas',
            new_name='Aluno_Turma',
        ),
        migrations.RenameModel(
            old_name='ObservacoesAluno',
            new_name='Observacoes_Aluno',
        ),
    ]
