# Generated by Django 4.2.20 on 2025-05-07 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0014_rename_alunosturmas_aluno_turma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacoes_aluno',
            name='descricao',
            field=models.CharField(default='Nenhuma observação registrada.', max_length=1000, verbose_name='Descrição da Observação'),
        ),
        migrations.AlterField(
            model_name='observacoes_aluno',
            name='tipo',
            field=models.CharField(choices=[('laudo', 'Laudo'), ('comportamento', 'Comportamento'), ('saude', 'Saúde'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Tipo de Observação'),
        ),
        migrations.AlterField(
            model_name='resultado_avaliacoes',
            name='avaliacao1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota da 1° avaliação'),
        ),
        migrations.AlterField(
            model_name='resultado_avaliacoes',
            name='avaliacao2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota da 2° avaliação'),
        ),
        migrations.AlterField(
            model_name='resultado_avaliacoes',
            name='avaliacao3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota da 3° avaliação'),
        ),
        migrations.AlterField(
            model_name='resultado_avaliacoes',
            name='avaliacao4',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota da 4° avaliação'),
        ),
        migrations.AlterField(
            model_name='resultado_avaliacoes',
            name='media_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Média Final'),
        ),
    ]
