# Generated by Django 4.2.20 on 2025-05-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0015_alter_observacoes_aluno_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='tipo_avaliacao1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_avaliacao1', to='educacao.avaliacoes'),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='tipo_avaliacao2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_avaliacao2', to='educacao.avaliacoes'),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='tipo_avaliacao3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_avaliacao3', to='educacao.avaliacoes'),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='tipo_avaliacao4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_avaliacao4', to='educacao.avaliacoes'),
        ),
    ]
