# Generated by Django 4.2.20 on 2025-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educacao', '0016_resultado_avaliacoes_tipo_avaliacao1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='status_avaliacao1',
            field=models.CharField(choices=[('capacitado', 'Capacitado'), ('naocapacitado', 'Não Capacitado')], editable=False, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='status_avaliacao2',
            field=models.CharField(choices=[('capacitado', 'Capacitado'), ('naocapacitado', 'Não Capacitado')], editable=False, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='status_avaliacao3',
            field=models.CharField(choices=[('capacitado', 'Capacitado'), ('naocapacitado', 'Não Capacitado')], editable=False, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='resultado_avaliacoes',
            name='status_avaliacao4',
            field=models.CharField(choices=[('capacitado', 'Capacitado'), ('naocapacitado', 'Não Capacitado')], editable=False, max_length=13, null=True),
        ),
    ]
