# Generated by Django 4.2.20 on 2025-04-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo_conta', models.CharField(choices=[('adm', 'Administrador'), ('ass', 'Assistente Administrativo'), ('dir', 'Diretor'), ('pro', 'Professor')], max_length=3)),
                ('dt_inlusao', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_user', to=settings.AUTH_USER_MODEL)),
                ('user_inclusao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pessoa_user_inclusao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
