# Generated by Django 4.2.20 on 2025-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_pessoa_user_inclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_conta',
            field=models.CharField(choices=[('adm', 'Administrador'), ('ass', 'Assistente Administrativo'), ('dir', 'Diretor'), ('pro', 'Auxiliar Escolar')], max_length=3),
        ),
    ]
